sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - npm install less -g
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix node
  - haxelib run travix neko
  - haxelib run travix neko -dce full
env:
  - secure: "rpavM8OmDE8HY4+5+PTYGqVoM4xcS91ODhL0g7Mi0ZTj/3O82gljlhIgTHdsdDsQ8k9sx99jVfdcdofH4t9uOqWXeZCSDiI35MrNrseltRyTwdeP7DjUwE/b9C5Hh6ImPTbQadQb8gayBC5hCvW4gD8dV0YuqL1AGZKypxKlgtfp6v4eZNI1tGOObY/zE/dDxkvONdGmm7QBQSldI0jpYdBlH4nMQyk56pH2tGmUQVThyVmqRA4T3Bo9BfYuaqN5FzDfIdACtvskzkmPtEZ/zBK3rkEa2I98SlEyebg/PDb/tzxP5DGFKET9q5kpjp+NU4sMH5YmQLjjDewOlRLujXbr3B9r2fmwKDDLlCYIgwCOY+RmQ2NAalMLhCN2XPP+VNrqJEHBcpIiOnglIbaswYMNSe7RbfxMTn/SEQw/eukjznNhnov0h0i81kPy864soNQKp+Ezj5NrXE33RBgoVK0O5Zi4cZCVRPCrEH+Uq4kJildfKiZkhOXZIPG31AwUEXPFQBXp2eliQ9npkS0VjDVkM0xmYVvbmiplrZv7tHSZSy40GFnuvY33beZTNQau88LpaG7DzTC+1GN0voOmUnK12GgQUGBtEIzF/TN0owGbpSPhtbGb9IbWkFE4TeuojVBM0+XuhrW90d9YFb5O2bDmGQF23q2Va10XxxlkTs4="
